/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArtContestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getAllEntries"
      | "getCategoryVotes"
      | "getEntry"
      | "nextEntryId"
      | "scoreEntry"
      | "submitEntry"
      | "voteEntry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntryScored" | "EntrySubmitted" | "EntryVoted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEntries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryVotes",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEntryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoreEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEntry",
    values: [string, string, string, string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voteEntry",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextEntryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scoreEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteEntry", data: BytesLike): Result;
}

export namespace EntryScoredEvent {
  export type InputTuple = [entryId: BigNumberish, judge: AddressLike];
  export type OutputTuple = [entryId: bigint, judge: string];
  export interface OutputObject {
    entryId: bigint;
    judge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntrySubmittedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    contestant: AddressLike,
    title: string
  ];
  export type OutputTuple = [
    entryId: bigint,
    contestant: string,
    title: string
  ];
  export interface OutputObject {
    entryId: bigint;
    contestant: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryVotedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    judge: AddressLike,
    category: string
  ];
  export type OutputTuple = [entryId: bigint, judge: string, category: string];
  export interface OutputObject {
    entryId: bigint;
    judge: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtContest extends BaseContract {
  connect(runner?: ContractRunner | null): ArtContest;
  waitForDeployment(): Promise<this>;

  interface: ArtContestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllEntries: TypedContractMethod<[], [bigint[]], "view">;

  getCategoryVotes: TypedContractMethod<
    [entryId: BigNumberish, category: string],
    [string],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string[],
        string[],
        bigint,
        string
      ] & {
        id: bigint;
        contestant: string;
        title: string;
        descriptionHash: string;
        fileHash: string;
        tags: string[];
        categories: string[];
        timestamp: bigint;
        scoresHandle: string;
      }
    ],
    "view"
  >;

  nextEntryId: TypedContractMethod<[], [bigint], "view">;

  scoreEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitEntry: TypedContractMethod<
    [
      title: string,
      descriptionHash: string,
      fileHash: string,
      tags: string[],
      categories: string[]
    ],
    [bigint],
    "nonpayable"
  >;

  voteEntry: TypedContractMethod<
    [entryId: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllEntries"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCategoryVotes"
  ): TypedContractMethod<
    [entryId: BigNumberish, category: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string[],
        string[],
        bigint,
        string
      ] & {
        id: bigint;
        contestant: string;
        title: string;
        descriptionHash: string;
        fileHash: string;
        tags: string[];
        categories: string[];
        timestamp: bigint;
        scoresHandle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextEntryId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scoreEntry"
  ): TypedContractMethod<[entryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEntry"
  ): TypedContractMethod<
    [
      title: string,
      descriptionHash: string,
      fileHash: string,
      tags: string[],
      categories: string[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntryScored"
  ): TypedContractEvent<
    EntryScoredEvent.InputTuple,
    EntryScoredEvent.OutputTuple,
    EntryScoredEvent.OutputObject
  >;
  getEvent(
    key: "EntrySubmitted"
  ): TypedContractEvent<
    EntrySubmittedEvent.InputTuple,
    EntrySubmittedEvent.OutputTuple,
    EntrySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EntryVoted"
  ): TypedContractEvent<
    EntryVotedEvent.InputTuple,
    EntryVotedEvent.OutputTuple,
    EntryVotedEvent.OutputObject
  >;

  filters: {
    "EntryScored(uint256,address)": TypedContractEvent<
      EntryScoredEvent.InputTuple,
      EntryScoredEvent.OutputTuple,
      EntryScoredEvent.OutputObject
    >;
    EntryScored: TypedContractEvent<
      EntryScoredEvent.InputTuple,
      EntryScoredEvent.OutputTuple,
      EntryScoredEvent.OutputObject
    >;

    "EntrySubmitted(uint256,address,string)": TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
    EntrySubmitted: TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;

    "EntryVoted(uint256,address,string)": TypedContractEvent<
      EntryVotedEvent.InputTuple,
      EntryVotedEvent.OutputTuple,
      EntryVotedEvent.OutputObject
    >;
    EntryVoted: TypedContractEvent<
      EntryVotedEvent.InputTuple,
      EntryVotedEvent.OutputTuple,
      EntryVotedEvent.OutputObject
    >;
  };
}
